#!/usr/bin/env bash
# Script that installs Nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chmod -R 755 /var/www
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo ufw allow 'NginX HTTP'
sudo service nginx start
