#!/usr/bin/env bash
# Script that installs Nginx server, redirects /redirect_me and customizes 404 not found
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
chown -R "$USER":"$USER" /etc/nginx/sites-available/default
chown -R "$USER":"$USER" /var/www/html

NotFound=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location /redirect_me {
		return 301 https://github.com/;
	}
 	error_page 404 /404.html;
    	location /404 {
      		root /var/www/html;
      		internal;
    	}
}"

echo -e "$NotFound" > /etc/nginx/sites-available/default

service nginx start
