#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 and displays 'bad luck' on 4th, 'good luck' on 8th loop and 'best school' for other iterations

n=1
while (( n <= 10 ))
do
  
  if [[ "$n" == '4' ]]; then
    echo "bad luck"

  elif [[ "$n" == '8' ]]; then
    echo "good luck"
  
  else
    echo "Best School"
  fi
  ((n++))
done
