#!/usr/bin/env bash
# A script to Configure ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80.

sudo apt install ufw
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

sudo ufw enable
